### ISSUE TITLE
ERROR "Deprecation Listener added for a synchronous 'DOMNodeInserted'"

### ISSUE THREAD

**Issue by gjtorbett** [wiris/moodle-local_wirisquizzes#30]
Hello, I think I initially posted my problem in the wrong place.
I am with a new installation of Moodle 4.3, PHP 8.2 and WirisQuizzes 4.11.1 (2024032201).
When trying to add a question from the Wiris Quizzes package. I get the following error in the console.

[Deprecation]Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated () and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

It seems to come from the WIRIS service itself.

![image](https://github.com/wiris/moodle-local_wirisquizzes/assets/59968952/df0f71d8-a5f2-454b-9f92-08dfc46ae3d0)

I would greatly appreciate your help

**Comment by ptorrent-at-wiris** [comment]
Dear @gjtorbett , this issue should be fixed in our latest releases. Thanks for reporting it.
